In [1]:
import pandas as pd

In [2]:
import sys
print(sys.executable)

/Users/sowmyadadheech/Documents/DATA 515/project/venv/bin/python

In [5]:
food = pd.read_csv("/Users/sowmyadadheech/Documents/DATA 515/project/data/food/Emergency_Food_and_Meals_Seattle_and_King_County_20260220.csv")

food.head()

,Food Resource Type,Agency,Location,Operational Status,Who They Serve,Address,Latitude,Longitude,Phone Number,Website,Days/Hours,Date Updated
0,Food Bank,Algona/Pacific Food Pantry,Algona/Pacific Food Pantry - Food Distribution...,Open,General Public,"603 3rd Ave SE, Pacific, WA 98047",47.265011,-122.236771,(253)-351-0450,https://networks.whyhunger.org/organisation/41599,Tuesday,7/22/2025
1,Food Bank & Meal,Asian Counseling and Referral Service (ACRS),ACRS Food Bank and Meals,Open,General Public,"800 S Weller St, Seattle, WA 98004",47.584363,-122.330378,(206)-695-7510,https://acrs.org/services/aging-services-for-o...,"Wednesday, Friday",8/7/2025
2,Meal,Asian Counseling and Referral Service (ACRS),Club Bamboo and Hmong Senior Club,Open,Older Adults 60+ and Eligible Participants,"3639 Martin Luther King Jr Way S, Seattle, WA ...",47.570897,-122.297388,(206)-695-7510,https://www.acrs.org/services/aging-services-f...,"Monday, Tuesday, Wednesday, Thursday, Friday",8/7/2025
3,Meal,Asian Counseling and Referral Service (ACRS),Duoc Su Senior Nutrition Program,Open,Older Adults 60+ and Eligible Participants,"6924 42nd Ave S , Seattle, WA 98118",47.540000,-122.280317,(206)-695-7510,https://www.acrs.org/services/aging-services-f...,Saturday,7/21/2025
4,Meal,Asian Counseling and Referral Service (ACRS),Friendly Island of Tonga Seniors,Open,Older Adults 60+ and Eligible Participants,"4620 SW Graham St, Seattle, WA 98136",47.546979,-122.392267,(206)-695-7510,https://www.acrs.org/services/aging-services-f...,NaN,7/22/2025

In [6]:
food.info()

<class 'pandas.DataFrame'>
RangeIndex: 268 entries, 0 to 267
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Food Resource Type  268 non-null    str
 1   Agency              268 non-null    str
 2   Location            268 non-null    str
 3   Operational Status  268 non-null    str
 4   Who They Serve      268 non-null    str
 5   Address             268 non-null    str
 6   Latitude            232 non-null    float64
 7   Longitude           232 non-null    float64
 8   Phone Number        246 non-null    str
 9   Website             262 non-null    str
 10  Days/Hours          241 non-null    str
 11  Date Updated        268 non-null    str
dtypes: float64(2), str(10)
memory usage: 25.3 KB

In [7]:
food.describe()
food.isnull().sum()

Food Resource Type     0
Agency                 0
Location               0
Operational Status     0
Who They Serve         0
Address                0
Latitude              36
Longitude             36
Phone Number          22
Website                6
Days/Hours            27
Date Updated           0
dtype: int64

In [9]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [geopy]
Successfully installed geographiclib-2.1 geopy-2.4.1

In [10]:
from geopy.geocoders import Nominatim
from time import sleep

In [13]:
geolocator = Nominatim(user_agent="food_access_project")

for idx, row in food[food["Latitude"].isnull()].iterrows():
    location = geolocator.geocode(row["Address"])
    if location:
        food.at[idx, "Latitude"] = location.latitude
        food.at[idx, "Longitude"] = location.longitude
    sleep(1)

In [14]:
food.isnull().sum()

Food Resource Type     0
Agency                 0
Location               0
Operational Status     0
Who They Serve         0
Address                0
Latitude               2
Longitude              2
Phone Number          22
Website                6
Days/Hours            27
Date Updated           0
dtype: int64

In [16]:
food = food.dropna(subset=["Latitude", "Longitude"])

In [17]:
food["Phone Number"] = food["Phone Number"].fillna("Not Available")
food["Website"] = food["Website"].fillna("Not Available")
food["Days/Hours"] = food["Days/Hours"].fillna("Unknown")

In [18]:
food["Food Resource Type"] = food["Food Resource Type"].str.lower().str.strip()
food["Operational Status"] = food["Operational Status"].str.lower()

In [19]:
food["Address"] = food["Address"].str.title().str.strip()

In [20]:
food1 = food[
    (food["Latitude"] > 47) & 
    (food["Latitude"] < 48)
]

In [21]:
food1 = food1.drop_duplicates()

In [ ]:
food1.to_csv("../data/food/clean_food_resources.csv", index=False)

In [25]:
king_county = pd.read_csv("/Users/sowmyadadheech/Documents/DATA 515/project/data/clean_king_county_stops.csv")
king_county.head()

,stop_id,stop_code,stop_name,tts_stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station,stop_timezone,wheelchair_boarding
0,100,100,1St Ave & Spring St,First Avenue and Spring Street,NaN,47.605137,-122.336533,21,NaN,0,NaN,America/Los_Angeles,1
1,10005,10005,40Th Ave Ne & Ne 51St St,40th Avenue Northeast and Northeast 51st Street,NaN,47.665886,-122.284897,1,NaN,0,NaN,America/Los_Angeles,1
2,10010,10010,Ne 55Th St & 39Th Ave Ne,Northeast 55th Street and 39th Avenue Northeast,NaN,47.668579,-122.285667,1,NaN,0,NaN,America/Los_Angeles,1
3,10020,10020,Ne 55Th St & 37Th Ave Ne,Northeast 55th Street and 37th Avenue Northeast,NaN,47.668579,-122.288300,1,NaN,0,NaN,America/Los_Angeles,1
4,10030,10030,Ne 55Th St & 35Th Ave Ne,Northeast 55th Street and 35th Avenue Northeast,NaN,47.668579,-122.290512,1,NaN,0,NaN,America/Los_Angeles,1